/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FuncionarioController;
import controller.RecognizerController;
import controller.WebCamController;
import entity.Funcionario;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Carlos
 */
public class CadastraFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form CadastraFuncionario
     */
    public CadastraFuncionario(Window owner, ModalityType modalityType) {
        super(owner, modalityType);
        setLocationRelativeTo(owner);
        initComponents();
        centralizar();
    }
    
    private void centralizar() throws HeadlessException {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int x = (int) toolkit.getScreenSize().getWidth() / 2 - getWidth() / 2;
        int y = (int) toolkit.getScreenSize().getHeight()/ 2 - getHeight() / 2;
        setLocation(x, y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlRg = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlCpf1 = new javax.swing.JLabel();
        jlRg1 = new javax.swing.JLabel();
        lbNumeroFotos = new javax.swing.JLabel();
        numeroFotos = new javax.swing.JLabel();
        jbAdicionarFoto = new javax.swing.JButton();
        outputPanel = new BackgroudedPanel();
        jbLigarWebCam = new javax.swing.JButton();
        jtTel = new javax.swing.JFormattedTextField();
        jtCpf = new javax.swing.JFormattedTextField();
        jtPis = new javax.swing.JFormattedTextField();
        jtRg = new javax.swing.JFormattedTextField();

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNome.setText("Nome");

        jlCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCpf.setText("CPF");

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlRg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlRg.setText("RG");

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCancelar.setText("Voltar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlCpf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCpf1.setText("PIS:");

        jlRg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlRg1.setText("Telefone:");

        lbNumeroFotos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNumeroFotos.setText("Numero de Fotos:");

        numeroFotos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeroFotos.setText("0");

        jbAdicionarFoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbAdicionarFoto.setText("Adicionar Foto");
        jbAdicionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarFotoActionPerformed(evt);
            }
        });

        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        outputPanel.setPreferredSize(new java.awt.Dimension(320, 240));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        jbLigarWebCam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbLigarWebCam.setText("Ligar WebCam");
        jbLigarWebCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLigarWebCamActionPerformed(evt);
            }
        });

        try {
            jtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jtPis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########### ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtPis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtRg.setDocument(new PlainDocument() {
            //Armazena o número máximo de caracteres para o texto.
            private int maxChars = 15;

            @Override
            public void insertString(int offs, String str, AttributeSet a)
            throws BadLocationException {
                if(str != null && (getLength() + str.length() < maxChars)){
                    super.insertString(offs, str, a);
                }
            }
        });
        jtRg.setColumns(15);
        jtRg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlRg, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtRg, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jtCpf))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlCpf1)
                                    .addComponent(jlRg1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtPis, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(jtTel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNumeroFotos)
                                        .addGap(18, 18, 18)
                                        .addComponent(numeroFotos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbAdicionarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbLigarWebCam, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlRg)
                        .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf1)
                            .addComponent(jtPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpf))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRg1)
                            .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumeroFotos)
                            .addComponent(numeroFotos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLigarWebCam)
                        .addGap(18, 18, 18)
                        .addComponent(jbAdicionarFoto)
                        .addGap(18, 18, 18)
                        .addComponent(jbCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar))
                    .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
 
        String nome = jtNome.getText();
        String cpf = jtCpf.getText();
        String rg = jtRg.getText();
        String pis = jtPis.getText();
        String telefone = jtTel.getText();
        
        Funcionario funcionario = funcionarioController.getFuncionario();
        funcionario.setNome(nome);
        funcionario.setTelefone(telefone);
        funcionario.setIdentidade(rg);
        funcionario.setCpf(cpf);
        funcionario.setPis(pis);        
        
        if(funcionarioController.save()){
            JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Um erro aconteceu ao salvar");
        }
        recognizerController.learn(funcionario);
        funcionarioController.flush();
        
        pararWebCam();
        numeroFotos.setText("0");
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        pararWebCam();
        numeroFotos.setText("0");
        setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbLigarWebCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLigarWebCamActionPerformed
        if(!webCamController.isRunning()){
            webCamController.initWebCam(normalCapture);
        }
    }//GEN-LAST:event_jbLigarWebCamActionPerformed

    private void jbAdicionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarFotoActionPerformed
        if (webCamController.isRunning()) {
            Object rosto = recognizerController.getBiggestFace(webCamController.getSelectedImage());
            if (rosto != null) {
                if(funcionarioController.getFotos().isEmpty()){
                    funcionarioController.setFotoPrincipal(webCamController.getSelectedImage());
                }
                funcionarioController.addFoto(rosto);
                numeroFotos.setText("" + funcionarioController.getFotos().size());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Inicie a WebCam");
        }
    }//GEN-LAST:event_jbAdicionarFotoActionPerformed

    private void pararWebCam(){
         if(webCamController.isRunning()){
            webCamController.stopWebCam();
        }
    }
    
    private void limpar(){
        jtTel.setText("");
        jtCpf.setText("");
        jtNome.setText("");
        jtPis.setText("");
        jtRg.setText("");
    }
    
    private void updateImagePanel(BufferedImage image, JPanel panel) {
        ((BackgroudedPanel) panel).updateBackground(image);
    }
    
    private WebCamController        webCamController      = WebCamController.getDefaultInstance();
    private FuncionarioController   funcionarioController = new FuncionarioController();
    private RecognizerController    recognizerController  = new RecognizerController();
    
    private Runnable normalCapture = new Runnable() {
                @Override
                public void run() {
                    updateImagePanel(webCamController.getBufferedImage(), outputPanel);
                }
            };
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAdicionarFoto;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbLigarWebCam;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpf1;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRg1;
    private javax.swing.JFormattedTextField jtCpf;
    private javax.swing.JTextField jtNome;
    private javax.swing.JFormattedTextField jtPis;
    private javax.swing.JFormattedTextField jtRg;
    private javax.swing.JFormattedTextField jtTel;
    private javax.swing.JLabel lbNumeroFotos;
    private javax.swing.JLabel numeroFotos;
    private javax.swing.JPanel outputPanel;
    // End of variables declaration//GEN-END:variables
}
