/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FuncionarioController;
import entity.Funcionario;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;
import model.CaptionUtils;

/**
 *
 * @author Carlos
 */
public class EditaFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form EditaFuncionario
     */
    public EditaFuncionario(Window owner, ModalityType modalityType) {
        super(owner, modalityType);
        setLocationRelativeTo(owner);
        initComponents();
        centralizar();
    }
    
    private void centralizar() throws HeadlessException {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int x = (int) toolkit.getScreenSize().getWidth() / 2 - getWidth() / 2;
        int y = (int) toolkit.getScreenSize().getHeight()/ 2 - getHeight() / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtNome = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlRg2 = new javax.swing.JLabel();
        jtMatricula = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jtCpf = new javax.swing.JFormattedTextField();
        jtPis = new javax.swing.JFormattedTextField();
        jtRg = new javax.swing.JFormattedTextField();
        jlRg1 = new javax.swing.JLabel();
        jtTel = new javax.swing.JFormattedTextField();
        jlCpf = new javax.swing.JLabel();
        jlRg = new javax.swing.JLabel();
        jlCpf1 = new javax.swing.JLabel();

        setIconImages(IconUtils.getIcons());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(CAPTIONS.getString("WORKER_EDIT")));

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlNome.setText(CAPTIONS.getString("NAME"));

        jlRg2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlRg2.setText(CAPTIONS.getString("ID"));

        jtMatricula.setEditable(false);
        jtMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCancelar.setText(CAPTIONS.getString("CANCEL"));
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCadastrar.setText(CAPTIONS.getString("SINGUP"));
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbExcluir.setText(CAPTIONS.getString("DELETE"));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        try {
            jtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jtPis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########### ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtPis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## - ##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtRg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlRg1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlRg1.setText(CAPTIONS.getString("PHONE"));

        try {
            jtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlCpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCpf.setText(CAPTIONS.getString("DOCNUMBER"));

        jlRg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlRg.setText(CAPTIONS.getString("ID_DOC"));

        jlCpf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCpf1.setText(CAPTIONS.getString("SS_NUMBER"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlRg2)
                        .addGap(18, 18, 18)
                        .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNome)
                            .addComponent(jlCpf)
                            .addComponent(jlRg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbExcluir)
                                .addGap(11, 11, 11)
                                .addComponent(jbCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105)
                                                .addComponent(jlCpf1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlRg1)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtPis, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRg2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf1)
                            .addComponent(jtPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRg1)
                            .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jlCpf)
                        .addGap(18, 18, 18)
                        .addComponent(jlRg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbCadastrar)
                    .addComponent(jbExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed

        String nome = jtNome.getText();
        String cpf = jtCpf.getText();
        String rg = jtRg.getText();
        String pis = jtPis.getText();
        String telefone = jtTel.getText();
        
        funcionario.setNome(nome);
        funcionario.setTelefone(telefone);
        funcionario.setIdentidade(rg);
        funcionario.setCpf(cpf);
        funcionario.setPis(pis);

        funcionarioController.update();
        funcionarioController.flush();

        JOptionPane.showMessageDialog(null, "Alterado Realizado");

        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        funcionarioController.delete();
        JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso");
        limpar();
        setVisible(false);
    }//GEN-LAST:event_jbExcluirActionPerformed

    private FuncionarioController funcionarioController = new FuncionarioController();
    private Funcionario funcionario;
    
    private void limpar(){
        jtTel.setText("");
        jtCpf.setText("");
        jtNome.setText("");
        jtPis.setText("");
        jtRg.setText("");
    }

    public Funcionario getFuncionario() {
        return funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
        funcionarioController.setFuncionario(funcionario);
        jtCpf.setText(funcionario.getCpf());
        jtMatricula.setText(funcionario.getId().toString());
        jtNome.setText(funcionario.getNome());
        jtPis.setText(funcionario.getPis());
        jtRg.setText(funcionario.getIdentidade());
        jtTel.setText(funcionario.getTelefone());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpf1;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRg1;
    private javax.swing.JLabel jlRg2;
    private javax.swing.JFormattedTextField jtCpf;
    private javax.swing.JTextField jtMatricula;
    private javax.swing.JTextField jtNome;
    private javax.swing.JFormattedTextField jtPis;
    private javax.swing.JFormattedTextField jtRg;
    private javax.swing.JFormattedTextField jtTel;
    // End of variables declaration//GEN-END:variables
    private static CaptionUtils CAPTIONS;

}
