/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FuncionarioController;
import entity.Funcionario;
import java.awt.Dialog;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.CaptionUtils;

/**
 *
 * @author Carlos
 */
public class ListagemFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form ListagemFuncionario
     */
    public ListagemFuncionario(Window owner, ModalityType modalityType) {
        super(owner, modalityType);
        setLocationRelativeTo(owner);
        initComponents();
        preencherTabela();
        menuFuncionario.setFocusable(false);
        centralizar();
    }
    
    private void centralizar() throws HeadlessException {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int x = (int) toolkit.getScreenSize().getWidth() / 2 - getWidth() / 2;
        int y = (int) toolkit.getScreenSize().getHeight()/ 2 - getHeight() / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuFuncionario = new javax.swing.JPopupMenu();
        menuExcluirFuncionario = new javax.swing.JMenuItem();
        alterarFuncionario = new javax.swing.JMenuItem();
        verRegistros = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        menuExcluirFuncionario.setText("Excluir Funcionario");
        menuExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(menuExcluirFuncionario);

        alterarFuncionario.setText("Alterar Funcionario");
        alterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(alterarFuncionario);

        verRegistros.setText("Ver Registros");
        verRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRegistrosActionPerformed(evt);
            }
        });
        menuFuncionario.add(verRegistros);

        setIconImages(IconUtils.getIcons());
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                focusGained(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, CAPTIONS.getString("WORKERSLIST"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClick(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(CAPTIONS.getString("IDNUMBER"));
        jTable1.getColumnModel().getColumn(1).setHeaderValue(CAPTIONS.getString("NAME"));
        jTable1.getColumnModel().getColumn(2).setHeaderValue(CAPTIONS.getString("DOCNUMBER"));
        jTable1.getColumnModel().getColumn(3).setHeaderValue(CAPTIONS.getString("PHONE"));
        jTable1.getColumnModel().getColumn(4).setHeaderValue(CAPTIONS.getString("SSNUMBER"));
        jTable1.getColumnModel().getColumn(5).setHeaderValue(CAPTIONS.getString("ID_DOC"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClick
        if(evt.getClickCount() == 2){
            alterarFuncionario();
        }
        if(evt.getButton() == MouseEvent.BUTTON3){
            int linha = jTable1.rowAtPoint(evt.getPoint());
            ListSelectionModel model = jTable1.getSelectionModel();
            model.setSelectionInterval(linha, linha);
            menuFuncionario.setLocation(evt.getLocationOnScreen());
            menuFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_mouseClick

    private void focusGained(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_focusGained
        preencherTabela();
    }//GEN-LAST:event_focusGained

    private void menuExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirFuncionarioActionPerformed
        int index = jTable1.getSelectedRow();
        Funcionario f = funcionarios.get(index);
        controller.setFuncionario(f);        
        controller.delete();
        menuFuncionario.setVisible(false);
        preencherTabela();
        JOptionPane.showMessageDialog(null, "Funcionario excluido com sucesso");
    }//GEN-LAST:event_menuExcluirFuncionarioActionPerformed

    private void alterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioActionPerformed
        alterarFuncionario();
    }//GEN-LAST:event_alterarFuncionarioActionPerformed

    private void verRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRegistrosActionPerformed
        ListagemRegistros.getInstance().setFuncionario(getFuncionario());
        ListagemRegistros.getInstance().setVisible(true);
    }//GEN-LAST:event_verRegistrosActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        menuFuncionario.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    private void preencherTabela (){
        funcionarios = controller.getAll();
        Object[][] tabela = new Object[funcionarios.size()][6];
        for(int i = 0; i< funcionarios.size(); i++){
            int j = 0;
            tabela[i][j++]  = funcionarios.get(i).getId();
            tabela[i][j++]  = funcionarios.get(i).getNome();
            tabela[i][j++]  = funcionarios.get(i).getCpf();
            tabela[i][j++]  = funcionarios.get(i).getTelefone();
            tabela[i][j++]  = funcionarios.get(i).getPis();
            tabela[i][j++]  = funcionarios.get(i).getIdentidade();
        }
        DefaultTableModel model;
        model = new DefaultTableModel(tabela, colunas) {
          boolean[] canEdit = new boolean [] {
              false, false, false, false, false, false
          };

          @Override
          public boolean isCellEditable(int rowIndex, int columnIndex) {
              return canEdit [columnIndex];
          }
      };
        
        jTable1.setModel(model);
        jTable1.updateUI();
    }
    
    private EditaFuncionario editaFuncionario = new EditaFuncionario(this, Dialog.ModalityType.APPLICATION_MODAL);
    private FuncionarioController controller = new FuncionarioController();
    private List<Funcionario> funcionarios;
    private String[] colunas = new String [] {
        "Matrícula", "Nome", "CPF", "Telefone", "PIS", "Identidade"
    };
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menuExcluirFuncionario;
    private javax.swing.JPopupMenu menuFuncionario;
    private javax.swing.JMenuItem verRegistros;
    // End of variables declaration//GEN-END:variables
    private static CaptionUtils CAPTIONS;

    private void alterarFuncionario() {
        Funcionario f = getFuncionario();
        editaFuncionario.setFuncionario(f);
        editaFuncionario.setVisible(true);
    }

    private Funcionario getFuncionario() {
        int index = jTable1.getSelectedRow();
        Funcionario f = funcionarios.get(index);
        return f;
    }
}